# Generated by Django 3.2.8 on 2021-11-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Origin', models.CharField(max_length=30)),
                ('Flight_Distination', models.CharField(max_length=30)),
                ('Flight_Nomber', models.IntegerField(max_length=10)),
                ('Flight_Date', models.DateField()),
                ('Flight_Time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
