# Generated by Django 3.2.8 on 2021-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0002_flight_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Airline',
            field=models.CharField(choices=[('IR', 'iranair'), ('W5', 'mahan'), ('B9', 'airtour'), ('EP', 'aseman'), ('ZV', 'zagros'), ('Y9', 'kish'), ('QB', 'qeshm'), ('I3', 'ata'), ('JI', 'meraj'), ('HH', 'taban'), ('RV', 'caspian'), ('NV', 'karon'), ('IS', 'sepehran'), ('VR', 'varesh'), ('PR', 'flypersia')], max_length=2),
        ),
    ]
