# Generated by Django 3.2.8 on 2021-11-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0004_alter_flight_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Nomber',
            field=models.IntegerField(),
        ),
    ]
