# Generated by Django 3.2.8 on 2021-11-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0009_alter_flight_flight_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='is_valid',
        ),
    ]
