# Generated by Django 3.2.8 on 2021-11-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0010_remove_flight_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Distination',
            field=models.CharField(choices=[('THR', 'tehran'), ('ABD', 'abadan'), ('MHD', "mash'had"), ('SYZ', 'shiraz'), ('IFN', 'isfahan'), ('ZBR', 'chabahar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Origin',
            field=models.CharField(choices=[('THR', 'tehran'), ('ABD', 'abadan'), ('MHD', "mash'had"), ('SYZ', 'shiraz'), ('IFN', 'isfahan'), ('ZBR', 'chabahar')], max_length=30),
        ),
    ]
