# Generated by Django 3.2.8 on 2021-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0011_auto_20211109_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Airline',
            field=models.CharField(choices=[('iranair', 'iranair'), ('mahan', 'mahan'), ('airtour', 'airtour'), ('aseman', 'aseman'), ('zagros', 'zagros'), ('kish', 'kish'), ('qeshm', 'qeshm'), ('ata', 'ata'), ('meraj', 'meraj'), ('taban', 'taban'), ('caspian', 'caspian'), ('karoon', 'karon'), ('sepehran_', 'sepehran'), ('varesh', 'varesh'), ('flypersia', 'flypersia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Distination',
            field=models.CharField(choices=[('tehran', 'tehran'), ('abadan', 'abadan'), ('mashhad', "mash'had"), ('shiraz', 'shiraz'), ('isfahan', 'isfahan'), ('chabahar', 'chabahar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Origin',
            field=models.CharField(choices=[('tehran', 'tehran'), ('abadan', 'abadan'), ('mashhad', "mash'had"), ('shiraz', 'shiraz'), ('isfahan', 'isfahan'), ('chabahar', 'chabahar')], max_length=30),
        ),
    ]
