# Generated by Django 3.2.8 on 2021-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0012_auto_20211109_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Time',
            field=models.TimeField(),
        ),
    ]
